# Generated by Django 3.0.6 on 2020-05-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='short_description_emoji',
            field=models.IntegerField(),
        ),
    ]
