# Generated by Django 3.0.6 on 2020-05-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200512_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_emoji',
            field=models.IntegerField(),
        ),
    ]
