# Generated by Django 3.0.6 on 2020-05-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_section_links_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
